export const FETCH_DATA_REQUEST ="FETCH_DATA_REQUEST"
export const FETCH_DATA_SUCESS ="FETCH_DATA_SUCESS"
export const FETCH_DATA_FAILURE ="FETCH_DATA_FAILURE"

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCESS = "GET_SINGLE_PRODUCT_SUCESS"
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCESS = "ADD_TO_CART_SUCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const REMOVE_ITEM_FROM_CART_REQUEST = "REMOVE_ITEM_FROM_CART_REQUEST"
export const REMOVE_ITEM_FROM_CART_SUCESS = "REMOVE_ITEM_FROM_CART_SUCESS"
export const REMOVE_ITEM_FROM_CART_FAILURE = "REMOVE_ITEM_FROM_CART_FAILURE"
